### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by JohnLaidler** [daveake/HABExplora#1]
I have a Google Pixel 3a mobile phone, originally with Android 10 but it has recently updated itself to Android 11 Build number RP1A.200720.009. The Android version is reported as 11 not 11.01 or anything like that. I understand all recent Pixel phones are 64 bit but I'm not sure how to check on mine.

HABExplora will not open since the upgrade. I have uninstalled and re-installed it but the result is the same. On clicking on the app the HABExplora logo (balloon with map in a circle) appears very briefly then it vanishes and the phone's home screen reappears.

John Laidler

**Comment by daveake** [comment]
I believe that this is because something changed in Android 11 that means
that apps built by my dev software (Delphi 10.3)  do not work on it.

The latest Delphi (10.4) fixes this.  I can't test that till my phone (Moto
G8 Power) gets updated from 10 to 11, so when that happens I'll update
Delphi also, test on my phone, and if all OK I'll update the Google Play
distribution.

Dave

**Comment by JohnLaidler** [comment]
Thank you.  :)  If I need to use it before then I can use my tablet and
link that to the phone.

**Comment by KevWal** [comment]
Hi Both, I get the same issue on a Samsung Galaxy S10+ running Android 12. HABExplora starts to run, shows Loading, then Access Granted and then crashes within 1 second after that.  I get the same result trying to run HABPADD on the phone. 

I have tried clearing cache, clearing data, re installing, but no change.

Thanks very much
Kev

**Comment by daveake** [comment]
It needs the APK rebuilt with the latest Dev software for Android 12
support.  It's on my list ...

**Comment by daveake** [comment]
Fixed in V1.7.0 which is going to the play store now.

**Comment by JohnLaidler** [comment]
Many thanks, I'll download and install it when available.

John

**Comment by KevWal** [comment]
Thanks Dave, looking good.

Can I ask, is 'pRxTx' just part of HabExplora?
![Screenshot_20221020-162655](https://user-images.githubusercontent.com/2286500/196994759-d9f30c2b-bb14-4c36-88b6-c87532c5d10a.jpg)

Cheers
Kev

**Comment by daveake** [comment]
Never heard of "prxTx" !  I'll see if I can find out where that's coming
from.  I'm guessing it's something in the USB serial library and, if so,
hopefully I can override it.

I'm pretty sure I've only ever seen it say "HAB Explora".

Dave

**Comment by JohnLaidler** [comment]
I don't see that warning on my Pixel 3a running Android 12. Just connected
the LoraGo and all seems to work fine but not tried on a payload yet.

John

**Comment by KevWal** [comment]
Sorry, ignore me, it is something else installed on my phone trying to steal the USB serial connection...

Not sure why HabExplora doesn't bring up the 'always open with hab explora' box, but that's not an issue.

**Comment by daveake** [comment]
That's up to Android; the application just asks for permission to use the
device.
