### ISSUE TITLE
Stuck in Invalid floating point operation loop

### ISSUE THREAD

**Issue by KevWal** [daveake/HABExplora#2]
Hi Dave

I installed a fresh copy,  started configuring it and it suddenly got stuck in a loop showing the above error.

Samsung Galaxy S10 running Android 10.

Screenshot attached 
![Screenshot_20201025-083152](https://user-images.githubusercontent.com/2286500/97102449-8c08de00-169d-11eb-9c28-2b21c88d256f.jpg)
![Screenshot_20201025-083515](https://user-images.githubusercontent.com/2286500/97102455-96c37300-169d-11eb-85fc-b307af6427f2.jpg)
![Screenshot_20201025-083519](https://user-images.githubusercontent.com/2286500/97102459-9fb44480-169d-11eb-92e3-6d054bc854ae.jpg)
![Screenshot_20201025-083524](https://user-images.githubusercontent.com/2286500/97102462-a80c7f80-169d-11eb-9fc2-0d3230acaec4.jpg)
![Screenshot_20201025-083529](https://user-images.githubusercontent.com/2286500/97102469-afcc2400-169d-11eb-9ad8-69d2bccd16b6.jpg)

Thanks very much
Kevin

**Comment by KevWal** [comment]
A force close and restart and it is ok now, so I just tickled something in the first run...

**Comment by daveake** [comment]
There's a new release coming soon which hopefully will fix this.

**Comment by daveake** [comment]
Fixed in V1.7.0 which is going to the play store now.
